### ISSUE TITLE
Add "Usage documentation"

### ISSUE THREAD

**Issue by icaropires** [icaropires/vandor-rename#3]
## Tasks

- [x] Create section on readme `Installing`
- [x] Add command for installation (Possibly just a wget)
- [x] Create `Usage` section on readme
- [x] Add usage example with explanation for already renamed exercises
- [x] Add usage example with explanation for files renamed on short form
